----------------------- *관리자 계정*으로 WW_FINAL 계정 생성 -----------------------
--CREATE USER WW_FINAL IDENTIFIED BY WW_FINAL;
--GRANT RESOURCE, CONNECT TO WW_FINAL;
--------------------------------------------------------------------------------

-------------------------------- 테이블 삭제 관련 ---------------------------------
DROP TABLE RESERVATION; -- 예약
DROP TABLE ASSETS; -- 자산

DROP TABLE STUDENT_ATTENDANCE;   --출석표
DROP TABLE STUDENT;   --학생
DROP TABLE CLASS_WEEK;   --강의 주차
DROP TABLE CLASS_PLAN;   --강의계획표
DROP TABLE CLASS;   --강의
DROP TABLE CLASSROOM;   --강의실
DROP TABLE CLASS_DATA_LIKE; -- 강의자료 즐겨찾기
DROP TABLE CLASS_ATTACHMENT;   --강의첨부파일
DROP TABLE CLASS_DATA_ROOM;   --강의자료실
DROP TABLE CLASS_DATA_CATEGORY; --강의카테고리

DROP TABLE NOTICE_REPLY;  -- 공지사항 댓글
DROP TABLE NOTICE_ATTACHMENT;  -- 공지사항 첨부파일
DROP TABLE NOTICE;  -- 공지사항

DROP TABLE COMMUNITY_REPLY;  -- 커뮤니티 댓글
DROP TABLE COMMUNITY_LIKE;  -- 커뮤니티 좋아요
DROP TABLE COMMUNITY_ATTACHMENT;  -- 커뮤니티 첨부파일
DROP TABLE COMMUNITY_BOARD;  -- 커뮤니티 게시판
DROP TABLE COMMUNITY_GROUP;  -- 커뮤니티 그룹
DROP TABLE COMMUNITY;  -- 커뮤니티

DROP TABLE EMPLOYEE;  -- 사원
DROP TABLE DEPARTMENT; -- 부서
DROP TABLE JOB; -- 직급
-------------------------------- 시퀀스 삭제 관련 --------------------------------
DROP SEQUENCE SEQ_RNO; -- 예약 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_ANO; -- 자산 번호 발생시킬 시퀀스

DROP SEQUENCE SEQ_CDCNO; --강의카테고리 시퀀스
DROP SEQUENCE SEQ_CDNO;  -- 강의자료실 시퀀스
DROP SEQUENCE SEQ_CDLNO; --강의자료 즐겨찾기 시퀀스
DROP SEQUENCE SEQ_CANO;  -- 강의첨부파일 시퀀스
DROP SEQUENCE SEQ_CLRNO;  -- 강의실 시퀀스
DROP SEQUENCE SEQ_CNO;  -- 강의 시퀀스
DROP SEQUENCE SEQ_CPNO;  -- 강의계획표 시퀀스
DROP SEQUENCE SEQ_CWNO;  -- 강의주차 시퀀스
DROP SEQUENCE SEQ_SNO;  -- 학생 시퀀스
DROP SEQUENCE SEQ_SANO;  -- 출석표 시퀀스

DROP SEQUENCE SEQ_NPNO; -- 공지사항댓글 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_NANO; -- 공지사항첨부파일 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_NNO;  -- 공지사항 번호 발생시킬 시퀀스

DROP SEQUENCE SEQ_CRNO; -- 커뮤니티댓글 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_CLNO; -- 커뮤니티좋아요 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_CATNO; -- 커뮤니티첨부파일 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_CBNO; -- 커뮤니티게시글 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_CGNO; -- 커뮤니티그룹 번호 발생시킬 시퀀스
DROP SEQUENCE SEQ_CONO; -- 커뮤니티 번호 발생시킬 시퀀스

DROP SEQUENCE SEQ_ENO;  -- 사원번호 발생시킬 시퀀스
--------------------------------------------------------------------------------


--============================================================================--
---------------------------- EMPLOYEE 관련 테이블 생성 ----------------------------
--============================================================================--
-- 직급
CREATE TABLE JOB(
    JOB_CODE VARCHAR2(5) PRIMARY KEY,
    JOB_NAME VARCHAR2(35) NOT NULL
);

COMMENT ON COLUMN JOB.JOB_CODE IS '직급코드';
COMMENT ON COLUMN JOB.JOB_CODE IS '직급명';

-- 부서
CREATE TABLE DEPARTMENT(
    DEPT_CODE VARCHAR2(5) PRIMARY KEY,
    DEPT_NAME VARCHAR2(35) NOT NULL
);

COMMENT ON COLUMN DEPARTMENT.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_NAME IS '부서명';

-- 사원
CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER PRIMARY KEY,
    EMP_NAME VARCHAR2(20) NOT NULL,
    EMP_EMAIL VARCHAR2(50) NOT NULL,
    EMP_PWD VARCHAR2(300) NOT NULL,
    EMP_PHONE VARCHAR2(15) NOT NULL,
    EMP_AGE DATE NOT NULL,
    EMP_GENDER VARCHAR2(6) CHECK (EMP_GENDER IN('남자', '여자')),
    EMP_ADDRESS VARCHAR2(100),
    EMP_ENROLL_DATE DATE DEFAULT SYSDATE,
    EMP_CHANGE_DATE DATE DEFAULT SYSDATE,
    EMP_STATUS NUMBER DEFAULT 0,
    EMP_ONLINE_STATUS VARCHAR2(15),
    PROFILE_FILE_PATH VARCHAR2(1000) DEFAULT 'resources/employeeprofile/default-profile.png',
    JOB_CODE VARCHAR2(5) REFERENCES JOB(JOB_CODE),
    DEPT_CODE VARCHAR2(5) REFERENCES DEPARTMENT(DEPT_CODE)
);

COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '사원이름';
COMMENT ON COLUMN EMPLOYEE.EMP_EMAIL IS '사원이메일';
COMMENT ON COLUMN EMPLOYEE.EMP_PWD IS '사원비밀번호';
COMMENT ON COLUMN EMPLOYEE.EMP_PHONE IS '사원연락처';
COMMENT ON COLUMN EMPLOYEE.EMP_AGE IS '사원나이'; -- 생년월일 8자리
COMMENT ON COLUMN EMPLOYEE.EMP_GENDER IS '사원성별';
COMMENT ON COLUMN EMPLOYEE.EMP_ADDRESS IS '사원주소';
COMMENT ON COLUMN EMPLOYEE.EMP_ENROLL_DATE IS '입사일';
COMMENT ON COLUMN EMPLOYEE.EMP_CHANGE_DATE IS '변경일';
COMMENT ON COLUMN EMPLOYEE.EMP_STATUS IS '재직상태';
COMMENT ON COLUMN EMPLOYEE.EMP_ONLINE_STATUS IS '온라인상태';
COMMENT ON COLUMN EMPLOYEE.PROFILE_FILE_PATH IS '프로필이미지 파일경로';
COMMENT ON COLUMN EMPLOYEE.JOB_CODE IS '직급코드';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS '부서코드';

CREATE SEQUENCE SEQ_ENO
NOCACHE;


--============================================================================--
--------------------------- COMMUNITY 관련 테이블 생성 ---------------------------
--============================================================================--

------------------------- 커뮤니티 1
CREATE TABLE COMMUNITY(
    COMMUNITY_NO NUMBER PRIMARY KEY,
    COMMUNITY_NAME VARCHAR2(30) NOT NULL,
    COMMUNITY_POINT VARCHAR2(100),
    COMMUNITY_STATUS VARCHAR2(1) DEFAULT 'Y'
);

COMMENT ON COLUMN COMMUNITY.COMMUNITY_NO IS '커뮤니티번호';
COMMENT ON COLUMN COMMUNITY.COMMUNITY_NAME IS '커뮤니티이름';
COMMENT ON COLUMN COMMUNITY.COMMUNITY_POINT IS '커뮤니티설명';
COMMENT ON COLUMN COMMUNITY.COMMUNITY_STATUS IS '상태';

CREATE SEQUENCE SEQ_CONO
NOCACHE;

------------------------- 커뮤니티 그룹 2
CREATE TABLE COMMUNITY_GROUP(
    COMMUNITY_GROUP_NO NUMBER PRIMARY KEY,
    COMMUNITY_NO NUMBER REFERENCES COMMUNITY(COMMUNITY_NO) NOT NULL,
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL
);

COMMENT ON COLUMN COMMUNITY_GROUP.COMMUNITY_GROUP_NO IS '그룹번호';
COMMENT ON COLUMN COMMUNITY_GROUP.COMMUNITY_NO IS '커뮤니티번호';
COMMENT ON COLUMN COMMUNITY_GROUP.EMP_NO IS '사원번호';

CREATE SEQUENCE SEQ_CGNO
NOCACHE;

------------------------- 커뮤니티 게시글 3
CREATE TABLE COMMUNITY_BOARD(
    COMMUNITY_BOARD_NO NUMBER PRIMARY KEY,
    COMMUNITY_NO NUMBER REFERENCES COMMUNITY(COMMUNITY_NO) NOT NULL,
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL,
    COMMUNITY_BOARD_TITLE VARCHAR2(100) NOT NULL,
    COMMUNITY_BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    COMMUNITY_BOARD_COUNT NUMBER DEFAULT 0,
    COMMUNITY_BOARD_CREATE_DATE DATE DEFAULT SYSDATE,
    COMMUNITY_BOARD_STATUS VARCHAR2(1) DEFAULT 'Y',
    COMMUNITY_BOARD_REPLY_COUNT NUMBER DEFAULT 0,
    COMMUNITY_BOARD_LIKE_COUNT NUMBER DEFAULT 0
);

COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_BOARD_NO IS '글번호';
COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_NO IS '커뮤니티번호';
COMMENT ON COLUMN COMMUNITY_BOARD.EMP_NO IS '작성자';
COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_BOARD_TITLE IS '글제목';
COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_BOARD_COUNT IS '조회수';
COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_BOARD_CREATE_DATE IS '작성일';
COMMENT ON COLUMN COMMUNITY_BOARD.COMMUNITY_BOARD_STATUS IS '상태';

CREATE SEQUENCE SEQ_CBNO
NOCACHE;

------------------------- 커뮤니티 첨부파일 4
CREATE TABLE COMMUNITY_ATTACHMENT(
    COMMUNITY_FILE_NO NUMBER PRIMARY KEY,
    COMMUNITY_BOARD_NO NUMBER REFERENCES COMMUNITY_BOARD(COMMUNITY_BOARD_NO) NOT NULL,
    COMMUNITY_ORIGIN_NAME VARCHAR2(200) NOT NULL,
    COMMUNITY_CHANGE_NAME VARCHAR2(200) NOT NULL,
    COMMUNITY_FILE_PATH VARCHAR2(1000) NOT NULL,
    COMMUNITY_UPLOAD_DATE DATE DEFAULT SYSDATE,
    COMMUNITY_FILE_LEVEL NUMBER DEFAULT 0 CHECK (COMMUNITY_FILE_LEVEL IN(0, 1))
);

COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_FILE_NO IS '파일번호';
COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_BOARD_NO IS '글번호';
COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_FILE_PATH IS '파일경로';
COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN COMMUNITY_ATTACHMENT.COMMUNITY_FILE_LEVEL IS '파일레벨';

CREATE SEQUENCE SEQ_CATNO
NOCACHE;

------------------------- 좋아요 5
CREATE TABLE COMMUNITY_LIKE(
    COMMUNITY_LIKE_NO NUMBER PRIMARY KEY,
    COMMUNITY_BOARD_NO NUMBER REFERENCES COMMUNITY_BOARD(COMMUNITY_BOARD_NO) NOT NULL,
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL
);

COMMENT ON COLUMN COMMUNITY_LIKE.COMMUNITY_LIKE_NO IS '좋아요번호';
COMMENT ON COLUMN COMMUNITY_LIKE.COMMUNITY_BOARD_NO IS '글번호';
COMMENT ON COLUMN COMMUNITY_LIKE.EMP_NO IS '사원번호';

CREATE SEQUENCE SEQ_CLNO
NOCACHE;

------------------------- 커뮤니티 댓글 6
CREATE TABLE COMMUNITY_REPLY(
    COMMUNITY_REPLY_NO NUMBER PRIMARY KEY,
    COMMUNITY_BOARD_NO NUMBER REFERENCES COMMUNITY_BOARD(COMMUNITY_BOARD_NO) NOT NULL,
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL,
    COMMUNITY_REPLY_COMMENT VARCHAR2(1000) NOT NULL,
    COMMUNITY_REPLY_CREATE_DATE DATE DEFAULT SYSDATE,
    COMMUNITY_REPLY_STATUS VARCHAR2(1) DEFAULT 'Y',
    PARENT_REPLY_NO NUMBER REFERENCES COMMUNITY_REPLY(COMMUNITY_REPLY_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN COMMUNITY_REPLY.COMMUNITY_REPLY_NO IS '댓글번호';
COMMENT ON COLUMN COMMUNITY_REPLY.COMMUNITY_BOARD_NO IS '글번호';
COMMENT ON COLUMN COMMUNITY_REPLY.EMP_NO IS '댓글작성자';
COMMENT ON COLUMN COMMUNITY_REPLY.COMMUNITY_REPLY_COMMENT IS '댓글내용';
COMMENT ON COLUMN COMMUNITY_REPLY.COMMUNITY_REPLY_CREATE_DATE IS '작성일';
COMMENT ON COLUMN COMMUNITY_REPLY.COMMUNITY_REPLY_STATUS IS '상태';
COMMENT ON COLUMN COMMUNITY_REPLY.PARENT_REPLY_NO IS '부모댓글번호';

CREATE SEQUENCE SEQ_CRNO
NOCACHE;

--============================================================================--
----------------------------- NOTICE 관련 테이블 생성 -----------------------------
--============================================================================--

-- 공지사항
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT VARCHAR(4000) NOT NULL,
    NOTICE_COUNT NUMBER DEFAULT 0,
    NOTICE_CREATE_DATE DATE DEFAULT SYSDATE,
    NOTICE_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (NOTICE_STATUS IN ('Y','N'))
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN NOTICE.EMP_NO IS '사원번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지사항제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항내용';
COMMENT ON COLUMN NOTICE.NOTICE_COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.NOTICE_CREATE_DATE IS '작성일';
COMMENT ON COLUMN NOTICE.NOTICE_STATUS IS '상태';
CREATE SEQUENCE SEQ_NNO
NOCACHE;


-- 공지사항 첨부파일
CREATE TABLE NOTICE_ATTACHMENT(
    NOTICE_FILE_NO NUMBER PRIMARY KEY,
    NOTICE_ORIGIN_NAME VARCHAR2(255) NOT NULL,
    NOTICE_CHANGE_NAME VARCHAR2(255) NOT NULL,
    NOTICE_FILE_PATH VARCHAR2(1000) NOT NULL,
    NOTICE_UPLOAD_DATE DATE DEFAULT SYSDATE,
    NOTICE_FILE_LEVEL NUMBER NOT NULL CHECK (NOTICE_FILE_LEVEL IN(0, 1)),
    NOTICE_ATTACHMENT_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (NOTICE_ATTACHMENT_STATUS IN('Y', 'N')),
    NOTICE_NO NUMBER REFERENCES NOTICE(NOTICE_NO) NOT NULL
);

COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_FILE_NO IS '파일번호';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_FILE_PATH IS '폴더경로';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_FILE_LEVEL IS '파일레벨';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_ATTACHMENT_STATUS IS ' 삭제여부';
COMMENT ON COLUMN NOTICE_ATTACHMENT.NOTICE_NO IS '공지사항번호';

CREATE SEQUENCE SEQ_NANO
NOCACHE;

-- 공지사항 댓글
CREATE TABLE NOTICE_REPLY(
    NOTICE_REPLY_NO NUMBER PRIMARY KEY,
    NOTICE_REPLY_CONTENT VARCHAR2(400) NOT NULL,
    NOTICE_REPLY_CREATE_DATE DATE DEFAULT SYSDATE,
    NOTICE_REPLY_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (NOTICE_REPLY_STATUS IN ('Y','N')),
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL,
    NOTICE_NO NUMBER REFERENCES NOTICE(NOTICE_NO) NOT NULL,
    PARENT_REPLY_NO NUMBER REFERENCES NOTICE_REPLY(NOTICE_REPLY_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN NOTICE_REPLY.NOTICE_REPLY_NO IS '댓글번호';
COMMENT ON COLUMN NOTICE_REPLY.NOTICE_REPLY_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE_REPLY.NOTICE_REPLY_CREATE_DATE IS '작성일';
COMMENT ON COLUMN NOTICE_REPLY.NOTICE_REPLY_STATUS IS '상태';
COMMENT ON COLUMN NOTICE_REPLY.EMP_NO IS '사원번호';
COMMENT ON COLUMN NOTICE_REPLY.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN NOTICE_REPLY.PARENT_REPLY_NO IS '부모댓글번호';

CREATE SEQUENCE SEQ_NPNO
NOCACHE;

--============================================================================--
------------------------------ 강의 관련 테이블 생성 ------------------------------
--============================================================================--

--강의자료실 카테고리
CREATE TABLE CLASS_DATA_CATEGORY(
    C_DATA_CATEGORY_NO NUMBER PRIMARY KEY, --카테고리 번호
    C_DATA_CATEGORY_NAME VARCHAR2(30) --카테고리 네임
);

COMMENT ON COLUMN CLASS_DATA_CATEGORY.C_DATA_CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CLASS_DATA_CATEGORY.C_DATA_CATEGORY_NAME IS '카테고리이름';
CREATE SEQUENCE SEQ_CDCNO
NOCACHE;

--강의자료실
CREATE TABLE CLASS_DATA_ROOM(
    C_DATA_NO NUMBER PRIMARY KEY, --자료번호
    REF_ENO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL, --작성자
    C_DATA_TITLE VARCHAR2(300), --자료제목
    C_DATA_CONTANT VARCHAR2(1000), --상세내용
    C_DATA_LIFE_TIME_NAME NUMBER DEFAULT 15, --보존연한
    C_DATA_DATE DATE DEFAULT SYSDATE, --등록일
    C_DATA_CATEGORY_NO NUMBER REFERENCES CLASS_DATA_CATEGORY(C_DATA_CATEGORY_NO) NOT NULL,
    C_DATA_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (C_DATA_STATUS IN('Y', 'N')) --상태
);

COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_NO IS '자료번호';
COMMENT ON COLUMN CLASS_DATA_ROOM.REF_ENO IS '작성자 외래키 번호';
COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_TITLE IS '자료제목';
COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_CONTANT IS '상세내용';
COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_LIFE_TIME_NAME IS '보존연한';
COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_DATE IS '등록일';
COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CLASS_DATA_ROOM.C_DATA_STATUS IS '상태';

CREATE SEQUENCE SEQ_CDNO
NOCACHE;

--강의 첨부파일
CREATE TABLE CLASS_ATTACHMENT(
    CLASS_FILE_NO NUMBER PRIMARY KEY, --강의파일번호
    REF_CDNO NUMBER REFERENCES CLASS_DATA_ROOM(C_DATA_NO) NOT NULL, --자료번호
    CLASS_ORIGIN_NAME VARCHAR2(255), --파일원본명
    CLASS_CHANGE_NAME VARCHAR2(255), --파일수정명
    CLASS_FILE_PATH VARCHAR2(1000), --폴더경로
    CLASS_FILE_LEVEL NUMBER DEFAULT 0 CHECK (CLASS_FILE_LEVEL IN(0, 1)), -- 기본 파일 0 대표 파일 1
    CLASS_FILE_SIZE VARCHAR(50), --파일사이즈
    CLASS_UPLOAD_DATE DATE DEFAULT SYSDATE, --업로드일
    CLASS_ATTACHMENT_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (CLASS_ATTACHMENT_STATUS IN('Y', 'N')) --자료삭제
);

COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_FILE_NO IS '강의파일번호';
COMMENT ON COLUMN CLASS_ATTACHMENT.REF_CDNO IS '자료번호';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_FILE_PATH IS '폴더경로';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_FILE_LEVEL IS '대표파일';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_FILE_SIZE IS '파일사이즈';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN CLASS_ATTACHMENT.CLASS_ATTACHMENT_STATUS IS '상태';

CREATE SEQUENCE SEQ_CANO
NOCACHE;

--강의 즐겨찾기
CREATE TABLE CLASS_DATA_LIKE(
    CD_LIKE_NO NUMBER PRIMARY KEY,
    CD_LIKE_EMP NUMBER REFERENCES EMPLOYEE(EMP_NO),
    CD_LIKE_CDR NUMBER REFERENCES CLASS_DATA_ROOM(C_DATA_NO),
    CD_LIKE_DATE DATE DEFAULT SYSDATE,
    CD_LIKE_STATUS VARCHAR(1) DEFAULT 'Y' CHECK(CD_LIKE_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN CLASS_DATA_LIKE.CD_LIKE_NO IS '강의자료즐겨찾기번호';
COMMENT ON COLUMN CLASS_DATA_LIKE.CD_LIKE_EMP IS '즐겨찾기 사원';
COMMENT ON COLUMN CLASS_DATA_LIKE.CD_LIKE_CDR IS '즐겨찾기 자료';
COMMENT ON COLUMN CLASS_DATA_LIKE.CD_LIKE_DATE IS '즐겨찾기 자료';
COMMENT ON COLUMN CLASS_DATA_LIKE.CD_LIKE_STATUS IS '즐겨찾기 자료';

CREATE SEQUENCE SEQ_CDLNO
NOCACHE;

--강의실
CREATE TABLE CLASSROOM(
    CLASSROOM_NO NUMBER PRIMARY KEY, --강의실번호
    CLASSROOM_CATAGORY_NAME VARCHAR2(10), -- 강의실이름
    CLASSROOM_TOTAL_NUMBER NUMBER-- 총수용인원
);

COMMENT ON COLUMN CLASSROOM.CLASSROOM_NO IS '강의실번호';
COMMENT ON COLUMN CLASSROOM.CLASSROOM_CATAGORY_NAME IS '강의실이름';
COMMENT ON COLUMN CLASSROOM.CLASSROOM_TOTAL_NUMBER IS '총수용인원';

CREATE SEQUENCE SEQ_CLRNO
NOCACHE;


--강의
CREATE TABLE CLASS(
    CLASS_NO NUMBER PRIMARY KEY, --강의번호
    CLASS_TITLE VARCHAR2(300), -- 강의명
    EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL, --사원(강사)번호
    CLASSROOM_NO NUMBER REFERENCES CLASSROOM(CLASSROOM_NO), --강의실번호
    CLASS_START_DATE DATE DEFAULT SYSDATE, --시작날짜
    CLASS_END_DATE DATE --종료날짜
);

COMMENT ON COLUMN CLASS.CLASS_NO IS '강의번호';
COMMENT ON COLUMN CLASS.EMP_NO IS '강의명';
COMMENT ON COLUMN CLASS.EMP_NO IS '강사번호';
COMMENT ON COLUMN CLASS.CLASSROOM_NO IS '강의실번호';
COMMENT ON COLUMN CLASS.CLASS_START_DATE IS '시작날짜';
COMMENT ON COLUMN CLASS.CLASS_END_DATE IS '종료날짜';

CREATE SEQUENCE SEQ_CNO
NOCACHE;


--강의계획표
CREATE TABLE CLASS_PLAN(
    CLASS_PLAN_NO NUMBER PRIMARY KEY, --강의계획표번호
    CLASS_CONTENT VARCHAR2(1000) --강의계획표내용
);

COMMENT ON COLUMN CLASS_PLAN.CLASS_PLAN_NO IS '강의 계획표 번호';
COMMENT ON COLUMN CLASS_PLAN.CLASS_CONTENT IS '강의계획표내용';

CREATE SEQUENCE SEQ_CPNO
NOCACHE;


-- 강의 주차
    CREATE TABLE CLASS_WEEK(
    CLASS_WEEK_NO NUMBER PRIMARY KEY, -- 강의주차 번호
    CLASS_WEEK VARCHAR2(30),  -- 강의주차
    CLASS_NO NUMBER REFERENCES CLASS(CLASS_NO),  -- 강의번호
    CLASS_PLAN_NO NUMBER REFERENCES CLASS_PLAN(CLASS_PLAN_NO)  --강의계획표번호
);

COMMENT ON COLUMN CLASS_WEEK.CLASS_WEEK_NO IS '강의주차 번호';
COMMENT ON COLUMN CLASS_WEEK.CLASS_WEEK IS '강의주차';
COMMENT ON COLUMN CLASS_WEEK.CLASS_NO IS '강의번호';
COMMENT ON COLUMN CLASS_WEEK.CLASS_PLAN_NO IS '강의계획표번호';

CREATE SEQUENCE SEQ_CWNO
NOCACHE;


--학생
CREATE TABLE STUDENT(
    STUDENT_NO NUMBER PRIMARY KEY, -- 학생번호
    CLASS_NO NUMBER REFERENCES CLASS(CLASS_NO) NOT NULL, -- 강의 번호
    STUDENT_NAME VARCHAR2(20) NOT NULL, -- 학생 이름
    STUDENT_PHONE VARCHAR2(15) NOT NULL, -- 학생 핸드폰 번호
    STUDENT_EMAIL VARCHAR2(40) NOT NULL UNIQUE, -- 학생이메일
    STUDENT_ADDRESS VARCHAR2(100), -- 학생 주소
    STUDENT_BIRTH VARCHAR2(14), -- 학생 생년월일
    STUDENT_GENDER VARCHAR2(3) DEFAULT '남' CHECK(STUDENT_GENDER IN('남', '여')) , -- 학생 성별
    STUDENT_MEMO VARCHAR2(100) NULL, -- 학생 메모
    ST_PROFILE_FILE_PATH VARCHAR2(1000),  -- 이미지경로
    STUDENT_ATTEMDAMCE VARCHAR2(6) DEFAULT '결석', -- 학생 출결
    STUDENT_ENROLL_DATE DATE DEFAULT SYSDATE, -- 생성날짜
    STUDENT_MODIFY_DATE DATE DEFAULT SYSDATE, -- 수정날짜
    STUDENT_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STUDENT_STATUS IN('Y', 'N')) -- 학생탈퇴
);

COMMENT ON COLUMN STUDENT.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN STUDENT.CLASS_NO IS '강의실 번호';
COMMENT ON COLUMN STUDENT.STUDENT_EMAIL IS '학생이메일';
COMMENT ON COLUMN STUDENT.STUDENT_NAME IS '학생이름';
COMMENT ON COLUMN STUDENT.STUDENT_PHONE IS '학생 핸드폰 번호';
COMMENT ON COLUMN STUDENT.STUDENT_ADDRESS IS '학생 주소';
COMMENT ON COLUMN STUDENT.STUDENT_BIRTH IS '학생생년월일';
COMMENT ON COLUMN STUDENT.STUDENT_GENDER IS '학생 성별';
COMMENT ON COLUMN STUDENT.STUDENT_MEMO IS '학생 메모';
COMMENT ON COLUMN STUDENT.STUDENT_ATTEMDAMCE IS '학생 출결';
COMMENT ON COLUMN STUDENT.STUDENT_ENROLL_DATE IS '생성날짜';
COMMENT ON COLUMN STUDENT.STUDENT_MODIFY_DATE IS '수정날짜';
COMMENT ON COLUMN STUDENT.STUDENT_STATUS IS '상태';

CREATE SEQUENCE SEQ_SNO
NOCACHE;


--출석표
CREATE TABLE STUDENT_ATTENDANCE(
    STT_ATT_GRAPH NUMBER PRIMARY KEY, --출석번호
    STUDENT_NO NUMBER REFERENCES STUDENT(STUDENT_NO) NOT NULL, --학생 번호
    STUDENT_ATT_NAME VARCHAR2(9),  --출결명
    STUDETNT_ATT_DATE DATE,  -- 출석날짜
    STUDENT_ATT_TIME DATE --시간
 
);

COMMENT ON COLUMN STUDENT_ATTENDANCE.STT_ATT_GRAPH IS '출석번호';
COMMENT ON COLUMN STUDENT_ATTENDANCE.STUDENT_NO IS '학생 번호';
COMMENT ON COLUMN STUDENT_ATTENDANCE.STUDENT_ATT_NAME IS '출결명';
COMMENT ON COLUMN STUDENT_ATTENDANCE.STUDETNT_ATT_DATE IS '출석날짜';
COMMENT ON COLUMN STUDENT_ATTENDANCE.STUDENT_ATT_TIME IS '시간';

CREATE SEQUENCE SEQ_SANO
NOCACHE;

--============================================================================--
------------------------------ 예약 관련 테이블 생성 ------------------------------
--============================================================================--
-- 자산
CREATE TABLE ASSETS (
   ASSETS_NO NUMBER PRIMARY KEY,
   ASSETS_NAME VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN ASSETS.ASSETS_NO IS '자산번호';
COMMENT ON COLUMN ASSETS.ASSETS_NAME IS '자산명';

CREATE SEQUENCE SEQ_ANO
NOCACHE;

-- 예약
CREATE TABLE RESERVATION (
   RESERVATION_NO NUMBER PRIMARY KEY,
   ASSETS_NO NUMBER REFERENCES ASSETS(ASSETS_NO) NOT NULL,
   EMP_NO NUMBER REFERENCES EMPLOYEE(EMP_NO) NOT NULL,
   RESERVATION_NAME VARCHAR2(30) NOT NULL,
   START_TIME DATE NULL,
   END_TIME DATE NULL,
   START_DATE DATE NULL,
   END_DATE DATE NULL,
   DELETE_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (DELETE_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN RESERVATION.RESERVATION_NO IS '예약번호';
COMMENT ON COLUMN RESERVATION.ASSETS_NO IS '자산번호';
COMMENT ON COLUMN RESERVATION.EMP_NO IS '사원번호';
COMMENT ON COLUMN RESERVATION.RESERVATION_NAME IS '자산이름';
COMMENT ON COLUMN RESERVATION.START_TIME IS '시작시간';
COMMENT ON COLUMN RESERVATION.END_TIME IS '종료시간';
COMMENT ON COLUMN RESERVATION.START_DATE IS '시작일';
COMMENT ON COLUMN RESERVATION.END_DATE IS '종료일';
COMMENT ON COLUMN RESERVATION.DELETE_STATUS IS '상태';

CREATE SEQUENCE SEQ_RNO
NOCACHE;





--============================================================================--
---------------------------------- 트리거 생성 ----------------------------------
--============================================================================--



-- 커뮤니티 게시글 : 댓글수 UP
CREATE OR REPLACE TRIGGER TRG_RUP
AFTER INSERT ON COMMUNITY_REPLY
FOR EACH ROW
BEGIN
    UPDATE COMMUNITY_BOARD
    SET COMMUNITY_BOARD_REPLY_COUNT = COMMUNITY_BOARD_REPLY_COUNT + 1
    WHERE COMMUNITY_BOARD_NO = :NEW.COMMUNITY_BOARD_NO;
END;
/

-- 커뮤니티 게시글 : 댓글수 DOWN
CREATE OR REPLACE TRIGGER TRG_RDO
AFTER DELETE ON COMMUNITY_REPLY
FOR EACH ROW
BEGIN
    UPDATE COMMUNITY_BOARD
    SET COMMUNITY_BOARD_REPLY_COUNT = COMMUNITY_BOARD_REPLY_COUNT - 1
    WHERE COMMUNITY_BOARD_NO = :OLD.COMMUNITY_BOARD_NO;
END;
/

-- 커뮤니티 게시글 : 좋아요수 UP
CREATE OR REPLACE TRIGGER TRG_LUP
AFTER INSERT ON COMMUNITY_LIKE
FOR EACH ROW
BEGIN
    UPDATE COMMUNITY_BOARD
    SET COMMUNITY_BOARD_LIKE_COUNT = COMMUNITY_BOARD_LIKE_COUNT + 1
    WHERE COMMUNITY_BOARD_NO = :NEW.COMMUNITY_BOARD_NO;
END;
/

-- 커뮤니티 게시글 : 좋아요수 DOWN
CREATE OR REPLACE TRIGGER TRG_LDO
BEFORE DELETE ON COMMUNITY_LIKE
FOR EACH ROW
BEGIN
    UPDATE COMMUNITY_BOARD
    SET COMMUNITY_BOARD_LIKE_COUNT = COMMUNITY_BOARD_LIKE_COUNT - 1
    WHERE COMMUNITY_BOARD_NO = :OLD.COMMUNITY_BOARD_NO;
END;
/





COMMIT;